name: Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted]
    #services:
    #  docker:
    #   image: docker:dind
    #    options: --privileged
    #    volumes:
    #      - /var/run/docker.sock:/var/run/docker.sock:ro
    container: ubuntu:latest
    steps:
      - name: Echo from Alpine
        run: hostname && pwd && cat /etc/*release
