name: Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted]
    #steps:
    #  - name: Attempt dind
    #    run: docker run hello-world
    container: alpine:latest
    steps:
      - name: Get Alpine uname
        run: cat /etc/release*
