name: Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Run a one-line script
        run: uname -a
