name: Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ubuntu-job:
    runs-on: [self-hosted]
    container:
      image: ubuntu:latest
      volumes:
        - /_work:/github/home    
    steps:
      - name: Echo from Ubuntu subcontainer job
        run: hostname && pwd && cat /etc/*release
#  alpine-job:
#    runs-on: [self-hosted]
#    container:
#      image: alpine:latest
#      volumes:
#        - /_work:/_work
#        - /tmp/runner:/tmp/runner
#    steps:
#      - name: Echo from Alpine subcontainer job
#        run: hostname && pwd && cat /etc/*release
